_wandb:
    value:
        cli_version: 0.23.0
        e:
            kdq9jzomg0ysk2131wsvomkjvynbrq0r:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    memoryGb: 8
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "7516192768"
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "217897439232"
                email: sjanugopanstudy@gmail.com
                executable: /Users/jaanumacbook/Programming Save Folder/FYP/FastFed/.venv/bin/python3
                git:
                    commit: 0962d6320503f3e7a6f7af8136c1f33a585d729c
                    remote: https://github.com/FYP-G-16-UOR-FOE/FastFed.git
                host: Sundaramoorthys-MacBook-Air.local
                memory:
                    total: "8589934592"
                os: macOS-14.5-arm64-arm-64bit
                program: /Users/jaanumacbook/Programming Save Folder/FYP/FastFed/main.py
                python: CPython 3.12.1
                root: /Users/jaanumacbook/Programming Save Folder/FYP/FastFed
                startedAt: "2025-11-22T19:16:00.984672Z"
                writerId: kdq9jzomg0ysk2131wsvomkjvynbrq0r
        m: []
        python_version: 3.12.1
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 13
                - 16
            "4": 3.12.1
            "5": 0.23.0
            "12": 0.23.0
            "13": darwin-arm64
algorithm:
    value: FedAvg
clients:
    value: 20
dataset_distribution:
    value: Realistic Non-IID
device:
    value: cpu
fl_rounds:
    value: 150
local_epochs:
    value: 4
model:
    value: VGG
selected_clients:
    value: 10
